export const OTC_PAIRS = [
  "EUR/USD-OTC","GBP/USD-OTC","USD/JPY-OTC","USD/CHF-OTC","AUD/USD-OTC","NZD/USD-OTC","USD/CAD-OTC",
  "EUR/GBP-OTC","EUR/JPY-OTC","GBP/JPY-OTC","AUD/JPY-OTC","CHF/JPY-OTC","EUR/AUD-OTC","GBP/CHF-OTC",
  "EUR/CAD-OTC","GBP/CAD-OTC","AUD/CAD-OTC","NZD/JPY-OTC","CAD/JPY-OTC","EUR/NZD-OTC","GBP/AUD-OTC",
  "GBP/NZD-OTC","AUD/NZD-OTC","EUR/CHF-OTC","AUD/CHF-OTC","CAD/CHF-OTC","NZD/CHF-OTC",
  "XAU/USD-OTC","XAG/USD-OTC","WTI/USD-OTC","BRENT/USD-OTC","NATGAS/USD-OTC","COPPER/USD-OTC",
  "US30-OTC","US100-OTC","US500-OTC","DE30-OTC","UK100-OTC","FR40-OTC","JP225-OTC","AU200-OTC",
  "HK50-OTC","ES35-OTC","IT40-OTC","CHINA50-OTC",
  "BTC/USD-OTC","ETH/USD-OTC","LTC/USD-OTC","XRP/USD-OTC","ADA/USD-OTC","DOT/USD-OTC","LINK/USD-OTC",
  "BCH/USD-OTC","XLM/USD-OTC","UNI/USD-OTC","DOGE/USD-OTC","MATIC/USD-OTC","SOL/USD-OTC","AVAX/USD-OTC",
  "SHIB/USD-OTC","TRX/USD-OTC","ETC/USD-OTC","XMR/USD-OTC",
  "AAPL-OTC","TSLA-OTC","AMZN-OTC","MSFT-OTC","GOOGL-OTC","META-OTC","NFLX-OTC","NVDA-OTC",
  "AMD-OTC","INTC-OTC","BABA-OTC","NKE-OTC","DIS-OTC","PYPL-OTC","V-OTC","JPM-OTC","KO-OTC",
  "PFE-OTC","WMT-OTC","XOM-OTC","BA-OTC","T-OTC","VZ-OTC","IBM-OTC","CRM-OTC"
];
export const TIMEFRAMES = [1,2,3,5,15];